Move wrapper functions to applications
vanvalenlab/deepcell-tf pull request #429
Opened 2020-09-11 00:11 UTC by ngreenwald

## What
- Moves the simple wrapper functions which are application-specific to the applications file.
- Updates requirements.txt for new version of the toolbox, which this PR relies on

## Why
- These functions aren't broadly useful, and don't really belong in the toolbox. Moving them here also makes it easier to update things and doesn't require patches across repos. This will also be useful once this whole module gets moved to its own repo

## Remaining tasks
- Update weights file once new model is trained
- Update post-processing default parameters once HPS finishes

2020-09-11 21:22 UTC, ngreenwald commented
Added in new weights files, as well as the current settings I'm using for postprocessing. 
Updated the model and test functions to expect a 2 semantic heads per prediction instead of 4.

2020-09-11 23:40 UTC, willgraf requested changes
Looking at the redis-consumer PR makes me realize that we probably made a mistake and should keep the format_multiplex and multiplex wrappers in the toolbox - specifically so that they are able to be used by the applications AND the consumer. I did not realize how much they are used by the consumers.

I'll try to set up a PR that moves them back into the toolbox and we'll release a 0.7.1 (if that makes sense to you).

2020-09-12 01:41 UTC, willgraf requested changes

2020-09-12 01:41 UTC, willgraf commented on requirements-test.txt
> +pytest-mock
```suggestion
```

2020-09-12 01:41 UTC, willgraf commented on deepcell/applications/multiplex_segmentation_test.py
> +
```suggestion
```

2020-09-12 02:22 UTC, willgraf approved these changes

2020-09-12 02:24 UTC, merged