Update Dockerfile to jupyter lab
vanvalenlab/deepcell-tf pull request #637
Opened 2023-01-05 23:12 UTC by rdilip

## What
* Removed jupyter notebook call

2023-01-05 23:59 UTC, msschwartz21 submitted a review, later dismissed
I'm pretty sure we also need to update the requirements to include jupyterlab. Although our tests do use our docker image, we override the entrypoint, so the tests wouldn't catch that we are calling jupyter lab without installing it.

2023-01-06 00:00 UTC, msschwartz21 requested changes
See comment above

2023-01-06 00:16 UTC, rdilip commented
Update: the image builds and runs without any issues.

2023-01-06 00:16 UTC, msschwartz21 approved these changes

2023-01-06 00:20 UTC, merged